# Generated by Django 4.2.1 on 2023-05-25 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='Doctor',
            new_name='Doctor_name',
        ),
    ]
