# Generated by Django 4.2.1 on 2023-05-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(max_length=70)),
                ('Age', models.CharField(max_length=5)),
                ('BloodPressure', models.CharField(max_length=20)),
                ('BloodSugar', models.CharField(max_length=20)),
                ('RaysAndAnalysis', models.ImageField(upload_to='photos/%y/%m/%d')),
            ],
        ),
    ]
