# Generated by Django 4.2.1 on 2023-05-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='Diagnosis',
            field=models.TextField(default='Diagnosis'),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='Medications',
            field=models.TextField(default='Medications'),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='Notes',
            field=models.TextField(default='Notes'),
        ),
    ]
